export const projects = [
  {
    title: "Brushr Homebrewer",
    description: "Home brew community repository of beer recipes",
    image: '/images/Brushr.png',
    tags: ['Java', 'JavaScript', 'Bootstrap4', 'MySQL'],
    source: 'https://github.com/therandomfool/MidtermProject',
    visit: 'https://github.com/therandomfool/MidtermProject',
    id: 0,
  },
  {
    title: "CampFree",
    description: "Online directory of dispersed camping sites",
    image: '/images/campfree.png',
    tags: ['Java', 'JavaScript', 'Angular', 'MySQL'],
    source: 'https://github.com/therandomfool/FinalProject',
    visit: 'https://github.com/therandomfool/FinalProject',
    id: 1,
  },
  {
    title: "Restaurant Reservation App",
    description: "Restaurant reservation system with database",
    image: '/images/reservationT.png',
    tags: ['Java', 'JavaScript', 'Angular', 'MySQL'],
    source: 'https://github.com/therandomfool/EventTrackerProject',
    visit: 'https://github.com/therandomfool/EventTrackerProject',
    id: 2,
  },
  {
    title: "Tech HTML Email",
    description: "HTML Email coded for 80+ mail clients. Technology Template",
    image: '/images/techtemplate.gif',
    tags: ['HTML', 'CSS',],
    source: 'https://github.com/therandomfool/EventTrackerProject',
    visit: 'https://vibrant-williams-d535d8.netlify.app/',
    id: 3,
  },
  {
    title: "Style and Apparel HTML EMAIL",
    description: "HTML Email coded for 80+ mail clients. Style & Apparel Template",
    image: '/images/style.gif',
    tags: ['HTML', 'CSS',],
    source: 'https://github.com/therandomfool/Apparel-HTML-Email',
    visit: 'https://gallant-bohr-ebd0fa.netlify.app/',
    id: 4,
  },
  // {
  //   title: "HTML EMAIL placeholder",
  //   description: "Restaurant reservation system with database",
  //   image: '/images/reservationT.png',
  //   tags: ['HTML', 'CSS',],
  //   source: 'https://github.com/therandomfool/EventTrackerProject',
  //   visit: 'https://github.com/therandomfool/EventTrackerProject',
  //   id: 5,
  // },
  // {
  //   title: "HTML EMAIL placeholder",
  //   description: "Restaurant reservation system with database",
  //   image: '/images/reservationT.png',
  //   tags: ['HTML', 'CSS',],
  //   source: 'https://github.com/therandomfool/EventTrackerProject',
  //   visit: 'https://github.com/therandomfool/EventTrackerProject',
  //   id: 6,
  // },
  {
    title: "React Movie Search App",
    description: "Movie search app using themoviedb API",
    image: '/images/movie.gif',
    tags: ['React', 'JavaScript', 'CSS'],
    source: 'https://github.com/therandomfool/React-Movie-Search',
    visit: 'https://github.com/therandomfool/React-Movie-Search',
    id: 7,
  },
  {
    title: "Game Machine",
    description: "Desktop only selection of created JavaScript games",
    image: '/images/gamemachine.gif',
    tags: ['JavaScript', 'CSS', 'JQuery', 'P5.JS'],
    source: 'https://github.com/therandomfool/Game-Machine',
    visit: 'https://amazing-snyder-723a73.netlify.app/',
    id: 8,
  },
  {
    title: "Animated Icon Background",
    description: "Using icons from font awesome and CSS animation techniques",
    image: '/images/icon.gif',
    tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://github.com/therandomfool/Icon-Background-Animation-CSS',
    visit: 'https://github.com/therandomfool/Icon-Background-Animation-CSS',
    id: 9,
  },
  {
    title: "Mandlebrot Set Grayscale",
    description: "Plotting the points of the Mandlebrot Set to display with P5.JS",
    image: '/images/mandlebrotX.png',
    tags: ['JavaScript', 'CSS', 'P5.JS',],
    source: 'https://github.com/therandomfool/Mandlebrot-Set-With-P5.JS-Grayscale',
    visit: 'https://github.com/therandomfool/Mandlebrot-Set-With-P5.JS-Grayscale',
    id: 10,
  },
  {
    title: "3D Image Hover Card",
    description: "360 card rotation with image visable from front, & text on the back",
    image: '/images/3d.gif',
    tags: ['JavaScript', 'CSS', 'HTML',],
    source: 'https://github.com/therandomfool/Mandlebrot-Set-With-P5.JS-Grayscale',
    visit: 'https://github.com/therandomfool/Mandlebrot-Set-With-P5.JS-Grayscale',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my self-taught web dev journey', },
  { year: 2019, text: 'Worked as a intern frontend dev', },
  { year: 2020, text: 'Attended Full Stack Bootcamp', },
  { year: 2020, text: 'Freelancer for HTML Emails and Web Dev', },
  { year: 2021, text: 'Ready for my next challenge', },
];